CREATE  TABLE "players" ("ID" INTEGER PRIMARY KEY  NOT NULL ,
"player_name" VARCHAR,
"player_experience_points" INTEGER,
"player_str" INTEGER,
"player_hp" INTEGER, 
"player_level" INTEGER,
"player_attack" INTEGER,
"player_ac" INTEGER,
"player_item1" VARCHAR,
"item1_quanity" INTEGER, 
"player_weapon" VARCHAR,
"player_weapon_strength" INTEGER,
"player_armor" VARCHAR,
"magic_level" INTEGER);
